version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  python-app:
    build:
      context: .  # Путь к директории с Python-приложением
    container_name: my-python-app
    ports:
      - "8088:8088"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/mydb  # Настройки подключения к MongoDB