version: '1.0'
services:
  mongodb:
    image: mongo:7.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_name
      MONGO_INITDB_ROOT_PASSWORD: user_password

  python-app:
    build:
      context: .  # Путь к директории с Python-приложением
    container_name: my-python-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://user_name:user_password@mongodb:27017/mydb
