version: '1.0'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_name
      MONGO_INITDB_ROOT_PASSWORD: user_password

  python-app:
    build:
      context: .  # Путь к директории с Python-приложением
    container_name: my-python-app
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
